with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;    use Protobuf.Descriptor;

package body Codegen.Emit_Enum is

   ----------
   -- Emit --

   procedure Emit
     (E          : Protobuf.Descriptor.Enum_Descriptor;
      Pkg_Prefix : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Enum_Ident : constant String :=
        Codegen.Naming.To_Ada_Identifier (To_String (E.Enum_Name));
      Pkg_Name   : constant String := Pkg_Prefix & "." & Enum_Ident;
      Stem       : constant String := Codegen.Naming.To_File_Stem (Pkg_Name);
      Spec       : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, "package " & Pkg_Name & " is" & ASCII.LF);
      Append (Spec, "   pragma Pure;" & ASCII.LF);
      Append (Spec, ASCII.LF);

      --  type T is (...)
      Append (Spec, "   type T is" & ASCII.LF);
      Append (Spec, "     (");
      declare
         First : Boolean := True;
      begin
         for V of E.Values loop
            declare
               Value_Ident : constant String :=
                 Codegen.Naming.To_Ada_Identifier (To_String (V.Value_Name));
            begin
               if not First then
                  Append (Spec, "," & ASCII.LF & "      ");
               end if;
               Append (Spec, Value_Ident);
               First := False;
            end;
         end loop;
      end;
      Append (Spec, ");" & ASCII.LF);

      --  for T use (... => N, ...);
      Append (Spec, "   for T use" & ASCII.LF);
      Append (Spec, "     (");
      declare
         First : Boolean := True;
      begin
         for V of E.Values loop
            declare
               Value_Ident : constant String :=
                 Codegen.Naming.To_Ada_Identifier (To_String (V.Value_Name));
               Number_Img  : constant String := V.Number'Image;
               Number      : constant String :=
                 (if Number_Img (Number_Img'First) = ' '
                  then Number_Img (Number_Img'First + 1 .. Number_Img'Last)
                  else Number_Img);
            begin
               if not First then
                  Append (Spec, "," & ASCII.LF & "      ");
               end if;
               Append (Spec, Value_Ident & " => " & Number);
               First := False;
            end;
         end loop;
      end;
      Append (Spec, ");" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "end " & Pkg_Name & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);
   end Emit;

end Codegen.Emit_Enum;
