with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;   use Protobuf.Descriptor;

package body Codegen.Emit_Service is

   --  ".helloworld.HelloRequest" -> "Helloworld.Hello_Request"
   --  Drops the leading dot, splits on '.', converts each part.
   function Type_Ref_To_Ada (Proto_Type : String) return String;

   function Type_Ref_To_Ada (Proto_Type : String) return String is
      Result : Unbounded_String;
      Buf    : Unbounded_String;
      Start  : Natural := Proto_Type'First;
   begin
      if Start <= Proto_Type'Last and then Proto_Type (Start) = '.' then
         Start := Start + 1;
      end if;
      for I in Start .. Proto_Type'Last loop
         if Proto_Type (I) = '.' then
            Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
            Append (Result, '.');
            Buf := Null_Unbounded_String;
         else
            Append (Buf, Proto_Type (I));
         end if;
      end loop;
      Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
      return To_String (Result);
   end Type_Ref_To_Ada;

   --  Helper: collect distinct `with` clauses.
   procedure Add_With (Withs : in out Unbounded_String; Pkg : String) is
      Tag : constant String := "with " & Pkg & ";" & ASCII.LF;
   begin
      if Index (Withs, Tag) = 0 then
         Append (Withs, Tag);
      end if;
   end Add_With;

   function Method_Ada (M : Method_Descriptor) return String is
     (Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name)));

   function Has_Server_Streaming (S : Service_Descriptor) return Boolean;
   function Has_Server_Streaming (S : Service_Descriptor) return Boolean is
   begin
      for M of S.Methods loop
         if M.Server_Streaming then
            return True;
         end if;
      end loop;
      return False;
   end Has_Server_Streaming;

   procedure Emit_Base_Spec
     (S          : Service_Descriptor;
      Pkg_Name   : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector);

   procedure Emit_Base_Body
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector);

   procedure Emit_Dispatch
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector);

   procedure Emit_Client
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector);

   --------------------
   -- Emit_Base_Spec --
   --------------------

   procedure Emit_Base_Spec
     (S          : Service_Descriptor;
      Pkg_Name   : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Stem       : constant String := Codegen.Naming.To_File_Stem (Pkg_Name);
      Spec       : Unbounded_String;
      Withs      : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      for M of S.Methods loop
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;
      if Has_Server_Streaming (S) then
         Add_With (Withs, "GRPC.Transport");
      end if;

      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, Withs);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Pkg_Name & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "   --  Fully-qualified path used in the HTTP/2 :path header."
                  & ASCII.LF);
      for M of S.Methods loop
         Append (Spec,
           "   Path_" & Method_Ada (M)
           & " : constant String := """
           & "/" & Proto_Pkg & "." & To_String (S.Service_Name) & "/"
           & To_String (M.Method_Name) & """;" & ASCII.LF);
      end loop;

      Append (Spec, ASCII.LF);
      Append (Spec, "   type Service is abstract tagged limited null record;"
                  & ASCII.LF);
      Append (Spec, "   type Service_Access is access all Service'Class;"
                  & ASCII.LF);
      Append (Spec, ASCII.LF);

      --  Writer record per server-streaming method, declared before the
      --  abstract subprograms that take them as parameters.
      for M of S.Methods loop
         if M.Server_Streaming then
            Append (Spec,
              "   --  Output handle for server-streaming "
              & Method_Ada (M) & ". The user implementation calls" & ASCII.LF
              & "   --  Write zero or more times during the procedure body."
              & ASCII.LF
              & "   type " & Method_Ada (M) & "_Writer is tagged record"
              & ASCII.LF
              & "      Transport : access GRPC.Transport.Stream'Class;"
              & ASCII.LF
              & "   end record;" & ASCII.LF
              & "   procedure Write" & ASCII.LF
              & "     (Self     : in out " & Method_Ada (M) & "_Writer;"
              & ASCII.LF
              & "      Response : "
              & Type_Ref_To_Ada (To_String (M.Output_Type)) & ".T);"
              & ASCII.LF & ASCII.LF);
         end if;
      end loop;

      for M of S.Methods loop
         declare
            In_Ref : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type)) & ".T";
         begin
            if M.Server_Streaming then
               Append (Spec,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Self    : in out Service;" & ASCII.LF
                 & "      Request : " & In_Ref & ";" & ASCII.LF
                 & "      Writer  : not null access "
                 & Method_Ada (M) & "_Writer'Class)"
                 & " is abstract;" & ASCII.LF & ASCII.LF);
            else
               Append (Spec,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Self     : in out Service;" & ASCII.LF
                 & "      Request  : " & In_Ref & ";" & ASCII.LF
                 & "      Response : out "
                 & Type_Ref_To_Ada (To_String (M.Output_Type))
                 & ".T) is abstract;" & ASCII.LF & ASCII.LF);
            end if;
         end;
      end loop;

      Append (Spec, "end " & Pkg_Name & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);
   end Emit_Base_Spec;

   --------------------
   -- Emit_Base_Body --
   --------------------

   procedure Emit_Base_Body
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Stem      : constant String := Codegen.Naming.To_File_Stem (Pkg_Name);
      Body_Text : Unbounded_String;
      Withs     : Unbounded_String;
   begin
      if not Has_Server_Streaming (S) then
         return;
      end if;

      Add_With (Withs, "Protobuf.IO");
      for M of S.Methods loop
         if M.Server_Streaming then
            Add_With (Withs, Type_Ref_To_Ada (To_String (M.Output_Type)));
         end if;
      end loop;

      Append (Body_Text, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Body_Text, Withs);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "package body " & Pkg_Name & " is" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "   Max_Message : constant := 64 * 1024;"
                       & ASCII.LF);
      Append (Body_Text, ASCII.LF);

      for M of S.Methods loop
         if M.Server_Streaming then
            declare
               Out_Pkg : constant String :=
                 Type_Ref_To_Ada (To_String (M.Output_Type));
            begin
               Append (Body_Text,
                 "   procedure Write" & ASCII.LF
                 & "     (Self     : in out " & Method_Ada (M) & "_Writer;"
                 & ASCII.LF
                 & "      Response : " & Out_Pkg & ".T)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      Buf    : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Cursor : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      " & Out_Pkg
                 & ".Encode (Response, Buf, Cursor);" & ASCII.LF
                 & "      Self.Transport.Send_Message" & ASCII.LF
                 & "        (Buf (1 .. Cursor.Position), End_Stream => False);"
                 & ASCII.LF
                 & "   end Write;" & ASCII.LF & ASCII.LF);
            end;
         end if;
      end loop;

      Append (Body_Text, "end " & Pkg_Name & ";" & ASCII.LF);

      declare
         File_Entry : Plugin.Generated_File;
      begin
         File_Entry.File_Name := To_Unbounded_String (Stem & ".adb");
         File_Entry.Content   := Body_Text;
         Files.Append (File_Entry);
      end;
   end Emit_Base_Body;

   -------------------
   -- Emit_Dispatch --
   -------------------

   procedure Emit_Dispatch
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Disp_Pkg   : constant String := Pkg_Name & ".Dispatch";
      Stem       : constant String := Codegen.Naming.To_File_Stem (Disp_Pkg);
      Spec       : Unbounded_String;
      Body_Text  : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      --  Spec
      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, "with GRPC.Server;" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Disp_Pkg & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "   --  Register all methods of " & Pkg_Name
                  & ".Service on Server, dispatching" & ASCII.LF);
      Append (Spec, "   --  to Service. Bind once per server lifetime."
                  & ASCII.LF);
      Append (Spec, "   procedure Bind" & ASCII.LF);
      Append (Spec, "     (Server  : in out GRPC.Server.Instance;"
                  & ASCII.LF);
      Append (Spec, "      Service : " & Pkg_Name & ".Service_Access);"
                  & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "end " & Disp_Pkg & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);

      --  Body
      Append (Body_Text, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Body_Text, "with GRPC.Call;" & ASCII.LF);
      Append (Body_Text, "with GRPC.Transport;" & ASCII.LF);
      Append (Body_Text, "with Protobuf.IO;" & ASCII.LF);
      for M of S.Methods loop
         Append (Body_Text, "with "
                          & Type_Ref_To_Ada (To_String (M.Input_Type)) & ";"
                          & ASCII.LF);
         if not M.Server_Streaming then
            Append (Body_Text, "with "
                             & Type_Ref_To_Ada (To_String (M.Output_Type)) & ";"
                             & ASCII.LF);
         end if;
      end loop;
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "package body " & Disp_Pkg & " is" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "   Max_Message : constant := 64 * 1024;"
                       & ASCII.LF);
      Append (Body_Text, "   Bound : " & Pkg_Name & ".Service_Access;"
                       & ASCII.LF);
      Append (Body_Text, ASCII.LF);

      for M of S.Methods loop
         declare
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            if M.Server_Streaming then
               Append (Body_Text,
                 "   procedure " & Method_Ada (M) & "_Handler" & ASCII.LF
                 & "     (Stream : not null access GRPC.Transport.Stream'Class;"
                 & ASCII.LF
                 & "      Call   : in out GRPC.Call.Instance)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      pragma Unreferenced (Call);" & ASCII.LF
                 & "      Inbound  : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Last     : Protobuf.IO.Octet_Count;" & ASCII.LF
                 & "      Got      : Boolean;" & ASCII.LF
                 & "      Request  : " & In_Pkg & ".T;" & ASCII.LF
                 & "      Writer   : aliased " & Pkg_Name & "."
                 & Method_Ada (M) & "_Writer;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      --  Stream'Access here would fail the runtime"
                 & ASCII.LF
                 & "      --  accessibility check on the anonymous-access"
                 & ASCII.LF
                 & "      --  parameter; Unchecked_Access is sound because"
                 & ASCII.LF
                 & "      --  Writer is freed before Stream's frame ends."
                 & ASCII.LF
                 & "      Writer.Transport := Stream.all'Unchecked_Access;"
                 & ASCII.LF
                 & "      Stream.Receive_Message (Inbound, Last, Got);"
                 & ASCII.LF
                 & "      if not Got then" & ASCII.LF
                 & "         return;" & ASCII.LF
                 & "      end if;" & ASCII.LF
                 & "      " & In_Pkg & ".Decode (Inbound (1 .. Last), Request);"
                 & ASCII.LF
                 & "      Bound." & Method_Ada (M)
                 & " (Request, Writer'Unchecked_Access);" & ASCII.LF
                 & "   end " & Method_Ada (M) & "_Handler;" & ASCII.LF
                 & ASCII.LF);
            else
               Append (Body_Text,
                 "   procedure " & Method_Ada (M) & "_Handler" & ASCII.LF
                 & "     (Stream : not null access GRPC.Transport.Stream'Class;"
                 & ASCII.LF
                 & "      Call   : in out GRPC.Call.Instance)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      pragma Unreferenced (Call);" & ASCII.LF
                 & "      Inbound  : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Last     : Protobuf.IO.Octet_Count;" & ASCII.LF
                 & "      Got      : Boolean;" & ASCII.LF
                 & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
                 & "      Response : " & Out_Pkg & ".T;" & ASCII.LF
                 & "      Outbound : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Cursor   : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      Stream.Receive_Message (Inbound, Last, Got);"
                 & ASCII.LF
                 & "      if not Got then" & ASCII.LF
                 & "         return;" & ASCII.LF
                 & "      end if;" & ASCII.LF
                 & "      " & In_Pkg & ".Decode (Inbound (1 .. Last), Request);"
                 & ASCII.LF
                 & "      Bound." & Method_Ada (M)
                 & " (Request, Response);" & ASCII.LF
                 & "      " & Out_Pkg
                 & ".Encode (Response, Outbound, Cursor);" & ASCII.LF
                 & "      Stream.Send_Message" & ASCII.LF
                 & "        (Outbound (1 .. Cursor.Position),"
                 & " End_Stream => True);" & ASCII.LF
                 & "   end " & Method_Ada (M) & "_Handler;" & ASCII.LF
                 & ASCII.LF);
            end if;
         end;
      end loop;

      --  Bind procedure
      Append (Body_Text, "   procedure Bind" & ASCII.LF);
      Append (Body_Text, "     (Server  : in out GRPC.Server.Instance;"
                       & ASCII.LF);
      Append (Body_Text, "      Service : " & Pkg_Name & ".Service_Access)"
                       & ASCII.LF);
      Append (Body_Text, "   is" & ASCII.LF);
      Append (Body_Text, "   begin" & ASCII.LF);
      Append (Body_Text, "      Bound := Service;" & ASCII.LF);
      for M of S.Methods loop
         Append (Body_Text,
           "      GRPC.Server.Register_Method" & ASCII.LF
           & "        (Server, " & Pkg_Name & ".Path_" & Method_Ada (M)
           & ", " & Method_Ada (M) & "_Handler'Access);" & ASCII.LF);
      end loop;
      Append (Body_Text, "   end Bind;" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "end " & Disp_Pkg & ";" & ASCII.LF);

      declare
         Body_Entry : Plugin.Generated_File;
      begin
         Body_Entry.File_Name := To_Unbounded_String (Stem & ".adb");
         Body_Entry.Content   := Body_Text;
         Files.Append (Body_Entry);
      end;
   end Emit_Dispatch;

   -----------------
   -- Emit_Client --
   -----------------

   procedure Emit_Client
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Cli_Pkg    : constant String := Pkg_Name & ".Client";
      Stem       : constant String := Codegen.Naming.To_File_Stem (Cli_Pkg);
      Spec       : Unbounded_String;
      Body_Text  : Unbounded_String;
      Withs      : Unbounded_String;
      File_Entry : Plugin.Generated_File;

      Has_Stream : constant Boolean := Has_Server_Streaming (S);
   begin
      --  Spec
      Add_With (Withs, "GRPC.Channel");
      if Has_Stream then
         Add_With (Withs, "Ada.Finalization");
         Add_With (Withs, "Ada.Streams");
      end if;
      for M of S.Methods loop
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;

      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, Withs);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Cli_Pkg & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);

      --  Reader types per server-streaming method.
      for M of S.Methods loop
         if M.Server_Streaming then
            Append (Spec,
              "   --  Stream of "
              & Type_Ref_To_Ada (To_String (M.Output_Type)) & ".T values"
              & " from the server. Owns its body buffer;" & ASCII.LF
              & "   --  freed automatically when the reader goes out of scope."
              & ASCII.LF
              & "   type " & Method_Ada (M) & "_Reader is tagged limited"
              & " private;" & ASCII.LF & ASCII.LF);
         end if;
      end loop;

      for M of S.Methods loop
         declare
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            if M.Server_Streaming then
               Append (Spec,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Channel : GRPC.Channel.Instance;" & ASCII.LF
                 & "      Request : " & In_Pkg & ".T;" & ASCII.LF
                 & "      Reader  : out " & Method_Ada (M) & "_Reader);"
                 & ASCII.LF & ASCII.LF
                 & "   --  Read the next response message. Got=False at"
                 & " end of stream." & ASCII.LF
                 & "   procedure Read" & ASCII.LF
                 & "     (Self     : in out " & Method_Ada (M) & "_Reader;"
                 & ASCII.LF
                 & "      Response : out " & Out_Pkg & ".T;" & ASCII.LF
                 & "      Got      : out Boolean);" & ASCII.LF
                 & ASCII.LF);
            else
               Append (Spec,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Channel  : GRPC.Channel.Instance;" & ASCII.LF
                 & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
                 & "      Response : out " & Out_Pkg & ".T);" & ASCII.LF
                 & ASCII.LF);
            end if;
         end;
      end loop;

      if Has_Stream then
         Append (Spec, "private" & ASCII.LF & ASCII.LF);
         Append (Spec,
           "   type Octet_Array_Access is access"
           & " Ada.Streams.Stream_Element_Array;" & ASCII.LF & ASCII.LF);
         for M of S.Methods loop
            if M.Server_Streaming then
               Append (Spec,
                 "   type " & Method_Ada (M) & "_Reader is" & ASCII.LF
                 & "     new Ada.Finalization.Limited_Controlled with record"
                 & ASCII.LF
                 & "      Body_Bytes : Octet_Array_Access;" & ASCII.LF
                 & "      Position   : Ada.Streams.Stream_Element_Count := 1;"
                 & ASCII.LF
                 & "   end record;" & ASCII.LF
                 & "   overriding procedure Finalize" & ASCII.LF
                 & "     (Self : in out " & Method_Ada (M) & "_Reader);"
                 & ASCII.LF & ASCII.LF);
            end if;
         end loop;
      end if;

      Append (Spec, "end " & Cli_Pkg & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);

      --  Body
      Append (Body_Text, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Body_Text, "with Ada.Streams;" & ASCII.LF);
      Append (Body_Text, "with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;"
                       & ASCII.LF);
      if Has_Stream then
         Append (Body_Text, "with Ada.Unchecked_Deallocation;" & ASCII.LF);
      end if;
      Append (Body_Text, "with AWS;" & ASCII.LF);
      Append (Body_Text, "with AWS.Client;" & ASCII.LF);
      Append (Body_Text, "with AWS.Headers;" & ASCII.LF);
      Append (Body_Text, "with AWS.Response;" & ASCII.LF);
      Append (Body_Text, "with GRPC.Framing;" & ASCII.LF);
      Append (Body_Text, "with " & Pkg_Name & ";" & ASCII.LF);
      Append (Body_Text, "with Interfaces;" & ASCII.LF);
      Append (Body_Text, "with Protobuf.IO;" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "package body " & Cli_Pkg & " is" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "   use Ada.Streams;" & ASCII.LF);
      Append (Body_Text, "   use type Stream_Element_Offset;" & ASCII.LF);
      Append (Body_Text, "   Max_Message : constant := 64 * 1024;"
                       & ASCII.LF);
      Append (Body_Text, ASCII.LF);

      if Has_Stream then
         Append (Body_Text,
           "   procedure Free is new Ada.Unchecked_Deallocation"
           & ASCII.LF
           & "     (Object => Stream_Element_Array, Name => Octet_Array_Access);"
           & ASCII.LF & ASCII.LF);

         for M of S.Methods loop
            if M.Server_Streaming then
               Append (Body_Text,
                 "   overriding procedure Finalize" & ASCII.LF
                 & "     (Self : in out " & Method_Ada (M) & "_Reader)"
                 & " is" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      if Self.Body_Bytes /= null then" & ASCII.LF
                 & "         Free (Self.Body_Bytes);" & ASCII.LF
                 & "      end if;" & ASCII.LF
                 & "   end Finalize;" & ASCII.LF
                 & ASCII.LF);
            end if;
         end loop;
      end if;

      for M of S.Methods loop
         declare
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            if M.Server_Streaming then
               Append (Body_Text,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Channel : GRPC.Channel.Instance;" & ASCII.LF
                 & "      Request : " & In_Pkg & ".T;" & ASCII.LF
                 & "      Reader  : out " & Method_Ada (M) & "_Reader)"
                 & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      Payload : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Cursor  : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "      H       : AWS.Headers.List := AWS.Client.Empty_Header_List;"
                 & ASCII.LF
                 & "      R       : AWS.Response.Data;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      " & In_Pkg & ".Encode (Request, Payload, Cursor);"
                 & ASCII.LF
                 & "      declare" & ASCII.LF
                 & "         Frame : Stream_Element_Array (1 .. Cursor.Position"
                 & ASCII.LF
                 & "                                          + Stream_Element_Offset"
                 & ASCII.LF
                 & "                                              (GRPC.Framing.Header_Size));"
                 & ASCII.LF
                 & "         HC : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "         URL : constant String :=" & ASCII.LF
                 & "           ""http://"" & To_String (Channel.Host) & "":"""
                 & ASCII.LF
                 & "           & Channel.Port'Image" & ASCII.LF
                 & "               (Channel.Port'Image'First + 1 .. Channel.Port'Image'Last)"
                 & ASCII.LF
                 & "           & " & Pkg_Name & ".Path_" & Method_Ada (M) & ";"
                 & ASCII.LF
                 & "      begin" & ASCII.LF
                 & "         GRPC.Framing.Encode_Header" & ASCII.LF
                 & "           (Buffer => Frame," & ASCII.LF
                 & "            Cursor => HC," & ASCII.LF
                 & "            Length => Interfaces.Unsigned_32 (Cursor.Position),"
                 & ASCII.LF
                 & "            Flag   => 0);" & ASCII.LF
                 & "         Frame" & ASCII.LF
                 & "           (Frame'First + Stream_Element_Offset"
                 & " (GRPC.Framing.Header_Size)" & ASCII.LF
                 & "            .. Frame'Last) := Payload (1 .. Cursor.Position);"
                 & ASCII.LF
                 & "         AWS.Headers.Add (H, ""te"", ""trailers"");"
                 & ASCII.LF
                 & "         AWS.Headers.Add (H, ""grpc-encoding"", ""identity"");"
                 & ASCII.LF
                 & "         R := AWS.Client.Post" & ASCII.LF
                 & "           (URL          => URL," & ASCII.LF
                 & "            Data         => Frame," & ASCII.LF
                 & "            Content_Type => ""application/grpc+proto"","
                 & ASCII.LF
                 & "            Headers      => H," & ASCII.LF
                 & "            HTTP_Version => AWS.HTTPv2);" & ASCII.LF
                 & "         Reader.Body_Bytes :=" & ASCII.LF
                 & "           new Stream_Element_Array'(AWS.Response.Message_Body (R));"
                 & ASCII.LF
                 & "         Reader.Position := Reader.Body_Bytes'First;"
                 & ASCII.LF
                 & "      end;" & ASCII.LF
                 & "   end " & Method_Ada (M) & ";" & ASCII.LF
                 & ASCII.LF
                 & "   procedure Read" & ASCII.LF
                 & "     (Self     : in out " & Method_Ada (M) & "_Reader;"
                 & ASCII.LF
                 & "      Response : out " & Out_Pkg & ".T;" & ASCII.LF
                 & "      Got      : out Boolean)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      Header_Size : constant Stream_Element_Count :=" & ASCII.LF
                 & "        Stream_Element_Count (GRPC.Framing.Header_Size);" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      if Self.Body_Bytes = null" & ASCII.LF
                 & "        or else Self.Position + Header_Size - 1"
                 & " > Self.Body_Bytes'Last" & ASCII.LF
                 & "      then" & ASCII.LF
                 & "         Got := False;" & ASCII.LF
                 & "         return;" & ASCII.LF
                 & "      end if;" & ASCII.LF
                 & "      declare" & ASCII.LF
                 & "         Frame  : Stream_Element_Array renames" & ASCII.LF
                 & "           Self.Body_Bytes (Self.Position .. Self.Body_Bytes'Last);"
                 & ASCII.LF
                 & "         RC     : Protobuf.IO.Read_Cursor;" & ASCII.LF
                 & "         Length : Interfaces.Unsigned_32;" & ASCII.LF
                 & "         Flag   : GRPC.Framing.Compression_Flag;" & ASCII.LF
                 & "      begin" & ASCII.LF
                 & "         GRPC.Framing.Decode_Header" & ASCII.LF
                 & "           (Buffer => Frame," & ASCII.LF
                 & "            Cursor => RC," & ASCII.LF
                 & "            Length => Length," & ASCII.LF
                 & "            Flag   => Flag);" & ASCII.LF
                 & "         " & Out_Pkg & ".Decode" & ASCII.LF
                 & "           (Frame" & ASCII.LF
                 & "              (Frame'First + RC.Position" & ASCII.LF
                 & "               .. Frame'First + RC.Position" & ASCII.LF
                 & "                  + Stream_Element_Offset (Length) - 1),"
                 & ASCII.LF
                 & "            Response);" & ASCII.LF
                 & "         Self.Position := Self.Position + Header_Size"
                 & ASCII.LF
                 & "                          + Stream_Element_Count (Length);"
                 & ASCII.LF
                 & "         Got := True;" & ASCII.LF
                 & "      end;" & ASCII.LF
                 & "   end Read;" & ASCII.LF
                 & ASCII.LF);
            else
               Append (Body_Text,
                 "   procedure " & Method_Ada (M) & ASCII.LF
                 & "     (Channel  : GRPC.Channel.Instance;" & ASCII.LF
                 & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
                 & "      Response : out " & Out_Pkg & ".T)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      Payload : Protobuf.IO.Octet_Array (1 .. Max_Message);"
                 & ASCII.LF
                 & "      Cursor  : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "      H       : AWS.Headers.List := AWS.Client.Empty_Header_List;"
                 & ASCII.LF
                 & "      R       : AWS.Response.Data;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      " & In_Pkg & ".Encode (Request, Payload, Cursor);"
                 & ASCII.LF
                 & "      declare" & ASCII.LF
                 & "         Frame : Stream_Element_Array (1 .. Cursor.Position"
                 & ASCII.LF
                 & "                                          + Stream_Element_Offset"
                 & ASCII.LF
                 & "                                              (GRPC.Framing.Header_Size));"
                 & ASCII.LF
                 & "         HC : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "         URL : constant String :=" & ASCII.LF
                 & "           ""http://"" & To_String (Channel.Host) & "":"""
                 & ASCII.LF
                 & "           & Channel.Port'Image" & ASCII.LF
                 & "               (Channel.Port'Image'First + 1 .. Channel.Port'Image'Last)"
                 & ASCII.LF
                 & "           & " & Pkg_Name & ".Path_" & Method_Ada (M) & ";"
                 & ASCII.LF
                 & "      begin" & ASCII.LF
                 & "         GRPC.Framing.Encode_Header" & ASCII.LF
                 & "           (Buffer => Frame," & ASCII.LF
                 & "            Cursor => HC," & ASCII.LF
                 & "            Length => Interfaces.Unsigned_32 (Cursor.Position),"
                 & ASCII.LF
                 & "            Flag   => 0);" & ASCII.LF
                 & "         Frame" & ASCII.LF
                 & "           (Frame'First + Stream_Element_Offset"
                 & " (GRPC.Framing.Header_Size)" & ASCII.LF
                 & "            .. Frame'Last) := Payload (1 .. Cursor.Position);"
                 & ASCII.LF
                 & "         AWS.Headers.Add (H, ""te"", ""trailers"");"
                 & ASCII.LF
                 & "         AWS.Headers.Add (H, ""grpc-encoding"", ""identity"");"
                 & ASCII.LF
                 & "         R := AWS.Client.Post" & ASCII.LF
                 & "           (URL          => URL," & ASCII.LF
                 & "            Data         => Frame," & ASCII.LF
                 & "            Content_Type => ""application/grpc+proto"","
                 & ASCII.LF
                 & "            Headers      => H," & ASCII.LF
                 & "            HTTP_Version => AWS.HTTPv2);" & ASCII.LF
                 & "         declare" & ASCII.LF
                 & "            Body_Bytes : constant Stream_Element_Array :="
                 & ASCII.LF
                 & "              AWS.Response.Message_Body (R);" & ASCII.LF
                 & "            RC     : Protobuf.IO.Read_Cursor;" & ASCII.LF
                 & "            Length : Interfaces.Unsigned_32;" & ASCII.LF
                 & "            Flag   : GRPC.Framing.Compression_Flag;"
                 & ASCII.LF
                 & "         begin" & ASCII.LF
                 & "            if Body_Bytes'Length < GRPC.Framing.Header_Size then"
                 & ASCII.LF
                 & "               raise Program_Error with"
                 & " ""response too short for gRPC frame"";" & ASCII.LF
                 & "            end if;" & ASCII.LF
                 & "            GRPC.Framing.Decode_Header" & ASCII.LF
                 & "              (Buffer => Body_Bytes," & ASCII.LF
                 & "               Cursor => RC," & ASCII.LF
                 & "               Length => Length," & ASCII.LF
                 & "               Flag   => Flag);" & ASCII.LF
                 & "            " & Out_Pkg & ".Decode" & ASCII.LF
                 & "              (Body_Bytes" & ASCII.LF
                 & "                 (Body_Bytes'First + RC.Position" & ASCII.LF
                 & "                  .. Body_Bytes'First + RC.Position" & ASCII.LF
                 & "                     + Stream_Element_Offset (Length) - 1),"
                 & ASCII.LF
                 & "               Response);" & ASCII.LF
                 & "         end;" & ASCII.LF
                 & "      end;" & ASCII.LF
                 & "   end " & Method_Ada (M) & ";" & ASCII.LF
                 & ASCII.LF);
            end if;
         end;
      end loop;

      Append (Body_Text, "end " & Cli_Pkg & ";" & ASCII.LF);

      declare
         Body_Entry : Plugin.Generated_File;
      begin
         Body_Entry.File_Name := To_Unbounded_String (Stem & ".adb");
         Body_Entry.Content   := Body_Text;
         Files.Append (Body_Entry);
      end;
   end Emit_Client;

   ----------
   -- Emit --
   ----------

   procedure Emit
     (S          : Service_Descriptor;
      Pkg_Prefix : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Svc_Ident : constant String :=
        Codegen.Naming.To_Ada_Identifier (To_String (S.Service_Name));
      Pkg_Name  : constant String := Pkg_Prefix & "." & Svc_Ident;
   begin
      Emit_Base_Spec (S, Pkg_Name, Proto_Pkg, Files);
      Emit_Base_Body (S, Pkg_Name, Files);
      Emit_Dispatch  (S, Pkg_Name, Files);
      Emit_Client    (S, Pkg_Name, Files);
   end Emit;

end Codegen.Emit_Service;
