with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;   use Protobuf.Descriptor;

package body Codegen.Emit_Client_V2 is

   function Type_Ref_To_Ada (Proto_Type : String) return String;
   function Type_Ref_To_Ada (Proto_Type : String) return String is
      Result : Unbounded_String;
      Buf    : Unbounded_String;
      Start  : Natural := Proto_Type'First;
   begin
      if Start <= Proto_Type'Last and then Proto_Type (Start) = '.' then
         Start := Start + 1;
      end if;
      for I in Start .. Proto_Type'Last loop
         if Proto_Type (I) = '.' then
            Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
            Append (Result, '.');
            Buf := Null_Unbounded_String;
         else
            Append (Buf, Proto_Type (I));
         end if;
      end loop;
      Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
      return To_String (Result);
   end Type_Ref_To_Ada;

   procedure Add_With (W : in out Unbounded_String; Pkg : String) is
      Tag : constant String := "with " & Pkg & ";" & ASCII.LF;
   begin
      if Index (W, Tag) = 0 then Append (W, Tag); end if;
   end Add_With;

   function MA (M : Method_Descriptor) return String is
     (Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name)));

   ----------
   -- Emit --
   ----------

   procedure Emit
     (S        : Protobuf.Descriptor.Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Cli_Pkg : constant String := Pkg_Name & ".Stub";
      Stem    : constant String := Codegen.Naming.To_File_Stem (Cli_Pkg);
      Spec    : Unbounded_String;
      Bod     : Unbounded_String;
      S_W     : Unbounded_String;
      B_W     : Unbounded_String;
   begin
      --  Collect withs.
      Add_With (S_W, "RFLX.RFLX_Types");
      Add_With (S_W, "Http2_Core.Connection");
      for M of S.Methods loop
         Add_With (S_W, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (S_W, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;

      Add_With (B_W, "Ada.Streams");
      Add_With (B_W, "Grpc_Core.Framing");
      Add_With (B_W, "Http2_Core.Hpack");
      Add_With (B_W, "Protobuf.IO");
      Add_With (B_W, Pkg_Name);
      for M of S.Methods loop
         Add_With (B_W, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (B_W, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;

      --  Spec ---------------------------------------------------
      Append (Spec, "--  Generated by protoc-gen-grpc-ada (v2 pure stack)."
                    & " Do not edit." & ASCII.LF);
      Append (Spec, S_W & ASCII.LF);
      Append (Spec, "package " & Cli_Pkg & " is" & ASCII.LF & ASCII.LF);

      Append (Spec, "   type Connection is limited private;" & ASCII.LF
                    & ASCII.LF);
      Append (Spec, "   procedure Connect" & ASCII.LF
                    & "     (C    : in out Connection;" & ASCII.LF
                    & "      Host : String;" & ASCII.LF
                    & "      Port : Natural := 50051);" & ASCII.LF
                    & ASCII.LF);

      for M of S.Methods loop
         if not M.Server_Streaming
           and then not M.Client_Streaming
         then
            declare
               In_T  : constant String :=
                 Type_Ref_To_Ada (To_String (M.Input_Type)) & ".T";
               Out_T : constant String :=
                 Type_Ref_To_Ada (To_String (M.Output_Type)) & ".T";
            begin
               Append (Spec,
                 "   procedure " & MA (M) & ASCII.LF
                 & "     (C        : in out Connection;" & ASCII.LF
                 & "      Request  : " & In_T & ";" & ASCII.LF
                 & "      Response : out " & Out_T & ");" & ASCII.LF
                 & ASCII.LF);
            end;
         end if;
      end loop;

      Append (Spec, "   procedure Close (C : in out Connection);"
                    & ASCII.LF & ASCII.LF);
      Append (Spec, "private" & ASCII.LF & ASCII.LF);
      Append (Spec, "   type Connection is limited record" & ASCII.LF
                    & "      H2           : Http2_Core.Connection.Connection;"
                    & ASCII.LF
                    & "      Conn_Buf     : RFLX.RFLX_Types.Bytes_Ptr;"
                    & ASCII.LF
                    & "      Inbound_Buf  : RFLX.RFLX_Types.Bytes_Ptr;"
                    & ASCII.LF
                    & "      Outgoing_Buf : RFLX.RFLX_Types.Bytes_Ptr;"
                    & ASCII.LF
                    & "      Authority    : String (1 .. 256)"
                    & " := (others => ASCII.NUL);" & ASCII.LF
                    & "      Authority_Len : Natural := 0;" & ASCII.LF
                    & "   end record;" & ASCII.LF & ASCII.LF);
      Append (Spec, "end " & Cli_Pkg & ";" & ASCII.LF);

      --  Body ---------------------------------------------------
      Append (Bod, "--  Generated by protoc-gen-grpc-ada (v2 pure stack)."
                   & " Do not edit." & ASCII.LF);
      Append (Bod, B_W & ASCII.LF);
      Append (Bod, "package body " & Cli_Pkg & " is" & ASCII.LF & ASCII.LF);
      Append (Bod, "   use type RFLX.RFLX_Types.Index;" & ASCII.LF);
      Append (Bod, "   use type Ada.Streams.Stream_Element_Offset;"
                   & ASCII.LF);
      Append (Bod, "   Buf_Size : constant := 64 * 1024 + 64;"
                   & ASCII.LF);
      Append (Bod, "   Max_Msg  : constant := 64 * 1024;"
                   & ASCII.LF & ASCII.LF);

      --  To_RFLX helper
      Append (Bod,
        "   function To_RFLX" & ASCII.LF
        & "     (S : Protobuf.IO.Octet_Array)" & ASCII.LF
        & "      return RFLX.RFLX_Types.Bytes" & ASCII.LF
        & "   is" & ASCII.LF
        & "      R : RFLX.RFLX_Types.Bytes"
        & " (1 .. RFLX.RFLX_Types.Index (S'Length));" & ASCII.LF
        & "   begin" & ASCII.LF
        & "      for I in R'Range loop" & ASCII.LF
        & "         R (I) := RFLX.RFLX_Types.Byte" & ASCII.LF
        & "           (S (S'First + Ada.Streams.Stream_Element_Offset"
        & " (I - R'First)));" & ASCII.LF
        & "      end loop;" & ASCII.LF
        & "      return R;" & ASCII.LF
        & "   end To_RFLX;" & ASCII.LF & ASCII.LF);

      --  Connect
      Append (Bod,
        "   procedure Connect" & ASCII.LF
        & "     (C    : in out Connection;" & ASCII.LF
        & "      Host : String;" & ASCII.LF
        & "      Port : Natural := 50051)" & ASCII.LF
        & "   is" & ASCII.LF
        & "   begin" & ASCII.LF
        & "      C.Conn_Buf := new RFLX.RFLX_Types.Bytes'"
        & "(1 .. Buf_Size => 0);" & ASCII.LF
        & "      C.Inbound_Buf := new RFLX.RFLX_Types.Bytes'"
        & "(1 .. Buf_Size => 0);" & ASCII.LF
        & "      C.Outgoing_Buf := new RFLX.RFLX_Types.Bytes'"
        & "(1 .. Buf_Size => 0);" & ASCII.LF
        & "      Http2_Core.Connection.Attach_Buffers" & ASCII.LF
        & "        (C.H2, C.Conn_Buf, C.Inbound_Buf, C.Outgoing_Buf);"
        & ASCII.LF
        & "      Http2_Core.Connection.Open (C.H2, Host, Port);"
        & ASCII.LF
        & "      C.Authority (1 .. Host'Length) := Host;" & ASCII.LF
        & "      C.Authority_Len := Host'Length;" & ASCII.LF
        & "   end Connect;" & ASCII.LF & ASCII.LF);

      --  Close
      Append (Bod,
        "   procedure Close (C : in out Connection) is" & ASCII.LF
        & "   begin" & ASCII.LF
        & "      Http2_Core.Connection.Close (C.H2);" & ASCII.LF
        & "      Http2_Core.Connection.Detach_Buffers" & ASCII.LF
        & "        (C.H2, C.Conn_Buf, C.Inbound_Buf, C.Outgoing_Buf);"
        & ASCII.LF
        & "   end Close;" & ASCII.LF & ASCII.LF);

      --  Per-method stubs (unary only for now)
      for M of S.Methods loop
         if not M.Server_Streaming
           and then not M.Client_Streaming
         then
            declare
               In_Pkg  : constant String :=
                 Type_Ref_To_Ada (To_String (M.Input_Type));
               Out_Pkg : constant String :=
                 Type_Ref_To_Ada (To_String (M.Output_Type));
               Path    : constant String :=
                 Pkg_Name & ".Path_" & MA (M);
            begin
               Append (Bod,
                 "   procedure " & MA (M) & ASCII.LF
                 & "     (C        : in out Connection;" & ASCII.LF
                 & "      Request  : " & In_Pkg & ".T;" & ASCII.LF
                 & "      Response : out " & Out_Pkg & ".T)" & ASCII.LF
                 & "   is" & ASCII.LF
                 & "      PB  : Protobuf.IO.Octet_Array (1 .. Max_Msg);"
                 & ASCII.LF
                 & "      Cur : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "   begin" & ASCII.LF
                 & "      " & In_Pkg & ".Encode (Request, PB, Cur);"
                 & ASCII.LF
                 & "      declare" & ASCII.LF
                 & "         PB_R : constant RFLX.RFLX_Types.Bytes :="
                 & ASCII.LF
                 & "           To_RFLX (PB (1 .. Cur.Position));" & ASCII.LF
                 & "         Frame : RFLX.RFLX_Types.Bytes"
                 & " (1 .. PB_R'Length + 5);" & ASCII.LF
                 & "         FL   : RFLX.RFLX_Types.Index;" & ASCII.LF
                 & "         FOK  : Boolean;" & ASCII.LF
                 & "      begin" & ASCII.LF
                 & "         Grpc_Core.Framing.Encode"
                 & " (Frame, PB_R, FL, FOK);" & ASCII.LF
                 & "         if not FOK then return; end if;" & ASCII.LF
                 & "         declare" & ASCII.LF
                 & "            Hdrs : constant Http2_Core.Hpack."
                 & "Header_Block (1 .. 6) :=" & ASCII.LF
                 & "              (Http2_Core.Hpack.Make_Header"
                 & " ("":method"", ""POST"")," & ASCII.LF
                 & "               Http2_Core.Hpack.Make_Header"
                 & " ("":scheme"", ""http"")," & ASCII.LF
                 & "               Http2_Core.Hpack.Make_Header"
                 & " ("":path"", " & Path & ")," & ASCII.LF
                 & "               Http2_Core.Hpack.Make_Header" & ASCII.LF
                 & "                 ("":authority"","
                 & " C.Authority (1 .. C.Authority_Len))," & ASCII.LF
                 & "               Http2_Core.Hpack.Make_Header"
                 & " (""content-type"", ""application/grpc"")," & ASCII.LF
                 & "               Http2_Core.Hpack.Make_Header"
                 & " (""te"", ""trailers""));" & ASCII.LF
                 & "            RH : Http2_Core.Hpack.Header_Block"
                 & " (1 .. 16);" & ASCII.LF
                 & "            RL : Natural;" & ASCII.LF
                 & "            RB : RFLX.RFLX_Types.Bytes"
                 & " (1 .. RFLX.RFLX_Types.Index (Max_Msg))"
                 & " := (others => 0);" & ASCII.LF
                 & "            BL : Natural;" & ASCII.LF
                 & "         begin" & ASCII.LF
                 & "            Http2_Core.Connection.Round_Trip" & ASCII.LF
                 & "              (C.H2, Hdrs,"
                 & " Frame (Frame'First .. FL)," & ASCII.LF
                 & "               RH, RL, RB, BL);" & ASCII.LF
                 & "            if BL >= 5 then" & ASCII.LF
                 & "               declare" & ASCII.LF
                 & "                  Resp_PB : Protobuf.IO.Octet_Array"
                 & ASCII.LF
                 & "                    (1 .. Ada.Streams."
                 & "Stream_Element_Offset (BL - 5));" & ASCII.LF
                 & "               begin" & ASCII.LF
                 & "                  for I in Resp_PB'Range loop"
                 & ASCII.LF
                 & "                     Resp_PB (I) :="
                 & " Protobuf.IO.Octet" & ASCII.LF
                 & "                       (RB (RFLX.RFLX_Types.Index"
                 & " (I) + 5));" & ASCII.LF
                 & "                  end loop;" & ASCII.LF
                 & "                  " & Out_Pkg
                 & ".Decode (Resp_PB, Response);" & ASCII.LF
                 & "               end;" & ASCII.LF
                 & "            end if;" & ASCII.LF
                 & "         end;" & ASCII.LF
                 & "      end;" & ASCII.LF
                 & "   end " & MA (M) & ";" & ASCII.LF & ASCII.LF);
            end;
         end if;
      end loop;

      Append (Bod, "end " & Cli_Pkg & ";" & ASCII.LF);

      declare
         SF : Plugin.Generated_File;
         BF : Plugin.Generated_File;
      begin
         SF.File_Name := To_Unbounded_String (Stem & ".ads");
         SF.Content   := Spec;
         BF.File_Name := To_Unbounded_String (Stem & ".adb");
         BF.Content   := Bod;
         Files.Append (SF);
         Files.Append (BF);
      end;
   end Emit;

end Codegen.Emit_Client_V2;
