with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;   use Protobuf.Descriptor;

package body Codegen.Emit_Service is

   --  ".helloworld.HelloRequest" -> "Helloworld.Hello_Request"
   --  Drops the leading dot, splits on '.', converts each part.
   function Type_Ref_To_Ada (Proto_Type : String) return String;

   function Type_Ref_To_Ada (Proto_Type : String) return String is
      Result : Unbounded_String;
      Buf    : Unbounded_String;
      Start  : Natural := Proto_Type'First;
   begin
      if Start <= Proto_Type'Last and then Proto_Type (Start) = '.' then
         Start := Start + 1;
      end if;
      for I in Start .. Proto_Type'Last loop
         if Proto_Type (I) = '.' then
            Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
            Append (Result, '.');
            Buf := Null_Unbounded_String;
         else
            Append (Buf, Proto_Type (I));
         end if;
      end loop;
      Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
      return To_String (Result);
   end Type_Ref_To_Ada;

   --  Helper: collect distinct `with` clauses.
   procedure Add_With (Withs : in out Unbounded_String; Pkg : String) is
      Tag : constant String := "with " & Pkg & ";" & ASCII.LF;
   begin
      if Index (Withs, Tag) = 0 then
         Append (Withs, Tag);
      end if;
   end Add_With;

   --  Emit the abstract base-class spec (server-side).
   procedure Emit_Base_Spec
     (S          : Service_Descriptor;
      Pkg_Name   : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector);

   --  Emit the dispatch package (server-side glue).
   procedure Emit_Dispatch
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector);

   --  Emit the client stub package.
   procedure Emit_Client
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector);

   ---------------------
   -- Emit_Base_Spec --
   ---------------------

   procedure Emit_Base_Spec
     (S          : Service_Descriptor;
      Pkg_Name   : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Stem       : constant String := Codegen.Naming.To_File_Stem (Pkg_Name);
      Spec       : Unbounded_String;
      Withs      : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      for M of S.Methods loop
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;

      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, Withs);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Pkg_Name & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "   --  Fully-qualified path used in the HTTP/2 :path header."
                  & ASCII.LF);
      for M of S.Methods loop
         Append (Spec,
           "   Path_"
           & Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name))
           & " : constant String := """
           & "/" & Proto_Pkg & "." & To_String (S.Service_Name) & "/"
           & To_String (M.Method_Name) & """;" & ASCII.LF);
      end loop;

      Append (Spec, ASCII.LF);
      Append (Spec, "   type Service is abstract tagged limited null record;"
                  & ASCII.LF);
      Append (Spec, "   type Service_Access is access all Service'Class;"
                  & ASCII.LF);
      Append (Spec, ASCII.LF);
      for M of S.Methods loop
         Append (Spec,
           "   procedure "
           & Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name))
           & ASCII.LF
           & "     (Self     : in out Service;" & ASCII.LF
           & "      Request  : "
           & Type_Ref_To_Ada (To_String (M.Input_Type)) & ".T;" & ASCII.LF
           & "      Response : out "
           & Type_Ref_To_Ada (To_String (M.Output_Type)) & ".T) is abstract;"
           & ASCII.LF & ASCII.LF);
      end loop;

      Append (Spec, "end " & Pkg_Name & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);
   end Emit_Base_Spec;

   -------------------
   -- Emit_Dispatch --
   -------------------

   procedure Emit_Dispatch
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Disp_Pkg   : constant String := Pkg_Name & ".Dispatch";
      Stem       : constant String := Codegen.Naming.To_File_Stem (Disp_Pkg);
      Spec       : Unbounded_String;
      Body_Text  : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      --  Spec
      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, "with GRPC.Server;" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Disp_Pkg & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "   --  Register all methods of " & Pkg_Name
                  & ".Service on Server, dispatching" & ASCII.LF);
      Append (Spec, "   --  to Service. Bind once per server lifetime."
                  & ASCII.LF);
      Append (Spec, "   procedure Bind" & ASCII.LF);
      Append (Spec, "     (Server  : in out GRPC.Server.Instance;"
                  & ASCII.LF);
      Append (Spec, "      Service : " & Pkg_Name & ".Service_Access);"
                  & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "end " & Disp_Pkg & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);

      --  Body
      Append (Body_Text, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Body_Text, "with GRPC.Call;" & ASCII.LF);
      Append (Body_Text, "with GRPC.Transport;" & ASCII.LF);
      Append (Body_Text, "with Protobuf.IO;" & ASCII.LF);
      for M of S.Methods loop
         Append (Body_Text, "with "
                          & Type_Ref_To_Ada (To_String (M.Input_Type)) & ";"
                          & ASCII.LF);
         Append (Body_Text, "with "
                          & Type_Ref_To_Ada (To_String (M.Output_Type)) & ";"
                          & ASCII.LF);
      end loop;
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "package body " & Disp_Pkg & " is" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "   Max_Message : constant := 64 * 1024;"
                       & ASCII.LF);
      Append (Body_Text, "   Bound : " & Pkg_Name & ".Service_Access;"
                       & ASCII.LF);
      Append (Body_Text, ASCII.LF);

      for M of S.Methods loop
         declare
            Method_Ident : constant String :=
              Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name));
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            Append (Body_Text,
              "   procedure " & Method_Ident & "_Handler" & ASCII.LF
              & "     (Stream : not null access GRPC.Transport.Stream'Class;"
              & ASCII.LF
              & "      Call   : in out GRPC.Call.Instance)" & ASCII.LF
              & "   is" & ASCII.LF
              & "      pragma Unreferenced (Call);" & ASCII.LF
              & "      Inbound  : Protobuf.IO.Octet_Array (1 .. Max_Message);"
              & ASCII.LF
              & "      Last     : Protobuf.IO.Octet_Count;" & ASCII.LF
              & "      Got      : Boolean;" & ASCII.LF
              & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
              & "      Response : " & Out_Pkg & ".T;" & ASCII.LF
              & "      Outbound : Protobuf.IO.Octet_Array (1 .. Max_Message);"
              & ASCII.LF
              & "      Cursor   : Protobuf.IO.Write_Cursor;" & ASCII.LF
              & "   begin" & ASCII.LF
              & "      Stream.Receive_Message (Inbound, Last, Got);"
              & ASCII.LF
              & "      if not Got then" & ASCII.LF
              & "         return;" & ASCII.LF
              & "      end if;" & ASCII.LF
              & "      " & In_Pkg & ".Decode (Inbound (1 .. Last), Request);"
              & ASCII.LF
              & "      Bound." & Method_Ident & " (Request, Response);"
              & ASCII.LF
              & "      " & Out_Pkg
              & ".Encode (Response, Outbound, Cursor);" & ASCII.LF
              & "      Stream.Send_Message" & ASCII.LF
              & "        (Outbound (1 .. Cursor.Position),"
              & " End_Stream => True);" & ASCII.LF
              & "   end " & Method_Ident & "_Handler;" & ASCII.LF
              & ASCII.LF);
         end;
      end loop;

      --  Bind procedure
      Append (Body_Text, "   procedure Bind" & ASCII.LF);
      Append (Body_Text, "     (Server  : in out GRPC.Server.Instance;"
                       & ASCII.LF);
      Append (Body_Text, "      Service : " & Pkg_Name & ".Service_Access)"
                       & ASCII.LF);
      Append (Body_Text, "   is" & ASCII.LF);
      Append (Body_Text, "   begin" & ASCII.LF);
      Append (Body_Text, "      Bound := Service;" & ASCII.LF);
      for M of S.Methods loop
         declare
            Method_Ident : constant String :=
              Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name));
         begin
            Append (Body_Text,
              "      GRPC.Server.Register_Method" & ASCII.LF
              & "        (Server, " & Pkg_Name & ".Path_" & Method_Ident
              & ", " & Method_Ident & "_Handler'Access);" & ASCII.LF);
         end;
      end loop;
      Append (Body_Text, "   end Bind;" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "end " & Disp_Pkg & ";" & ASCII.LF);

      declare
         Body_Entry : Plugin.Generated_File;
      begin
         Body_Entry.File_Name := To_Unbounded_String (Stem & ".adb");
         Body_Entry.Content   := Body_Text;
         Files.Append (Body_Entry);
      end;
   end Emit_Dispatch;

   -----------------
   -- Emit_Client --
   -----------------

   procedure Emit_Client
     (S        : Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Cli_Pkg    : constant String := Pkg_Name & ".Client";
      Stem       : constant String := Codegen.Naming.To_File_Stem (Cli_Pkg);
      Spec       : Unbounded_String;
      Body_Text  : Unbounded_String;
      Withs      : Unbounded_String;
      File_Entry : Plugin.Generated_File;
   begin
      --  Spec
      Add_With (Withs, "GRPC.Channel");
      for M of S.Methods loop
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Input_Type)));
         Add_With (Withs, Type_Ref_To_Ada (To_String (M.Output_Type)));
      end loop;

      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, Withs);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Cli_Pkg & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      for M of S.Methods loop
         declare
            Method_Ident : constant String :=
              Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name));
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            Append (Spec,
              "   procedure " & Method_Ident & ASCII.LF
              & "     (Channel  : GRPC.Channel.Instance;" & ASCII.LF
              & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
              & "      Response : out " & Out_Pkg & ".T);" & ASCII.LF
              & ASCII.LF);
         end;
      end loop;
      Append (Spec, "end " & Cli_Pkg & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);

      --  Body
      Append (Body_Text, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Body_Text, "with Ada.Streams;" & ASCII.LF);
      Append (Body_Text, "with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;"
                       & ASCII.LF);
      Append (Body_Text, "with AWS;" & ASCII.LF);
      Append (Body_Text, "with AWS.Client;" & ASCII.LF);
      Append (Body_Text, "with AWS.Headers;" & ASCII.LF);
      Append (Body_Text, "with AWS.Response;" & ASCII.LF);
      Append (Body_Text, "with GRPC.Framing;" & ASCII.LF);
      Append (Body_Text, "with " & Pkg_Name & ";" & ASCII.LF);
      Append (Body_Text, "with Interfaces;" & ASCII.LF);
      Append (Body_Text, "with Protobuf.IO;" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "package body " & Cli_Pkg & " is" & ASCII.LF);
      Append (Body_Text, ASCII.LF);
      Append (Body_Text, "   use Ada.Streams;" & ASCII.LF);
      Append (Body_Text, "   use type Stream_Element_Offset;" & ASCII.LF);
      Append (Body_Text, "   Max_Message : constant := 64 * 1024;"
                       & ASCII.LF);
      Append (Body_Text, ASCII.LF);

      for M of S.Methods loop
         declare
            Method_Ident : constant String :=
              Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name));
            In_Pkg  : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Pkg : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            Append (Body_Text,
              "   procedure " & Method_Ident & ASCII.LF
              & "     (Channel  : GRPC.Channel.Instance;" & ASCII.LF
              & "      Request  : " & In_Pkg  & ".T;" & ASCII.LF
              & "      Response : out " & Out_Pkg & ".T)" & ASCII.LF
              & "   is" & ASCII.LF
              & "      Payload : Protobuf.IO.Octet_Array (1 .. Max_Message);"
              & ASCII.LF
              & "      Cursor  : Protobuf.IO.Write_Cursor;" & ASCII.LF
              & "      H       : AWS.Headers.List := AWS.Client.Empty_Header_List;"
              & ASCII.LF
              & "      R       : AWS.Response.Data;" & ASCII.LF
              & "   begin" & ASCII.LF
              & "      " & In_Pkg & ".Encode (Request, Payload, Cursor);"
              & ASCII.LF
              & "      declare" & ASCII.LF
              & "         Frame : Stream_Element_Array (1 .. Cursor.Position"
              & ASCII.LF
              & "                                          + Stream_Element_Offset"
              & ASCII.LF
              & "                                              (GRPC.Framing.Header_Size));"
              & ASCII.LF
              & "         HC : Protobuf.IO.Write_Cursor;" & ASCII.LF
              & "         URL : constant String :=" & ASCII.LF
              & "           ""http://"" & To_String (Channel.Host) & "":""" & ASCII.LF
              & "           & Channel.Port'Image" & ASCII.LF
              & "               (Channel.Port'Image'First + 1 .. Channel.Port'Image'Last)"
              & ASCII.LF
              & "           & " & Pkg_Name & ".Path_" & Method_Ident & ";"
              & ASCII.LF
              & "      begin" & ASCII.LF
              & "         GRPC.Framing.Encode_Header" & ASCII.LF
              & "           (Buffer => Frame," & ASCII.LF
              & "            Cursor => HC," & ASCII.LF
              & "            Length => Interfaces.Unsigned_32 (Cursor.Position),"
              & ASCII.LF
              & "            Flag   => 0);" & ASCII.LF
              & "         Frame" & ASCII.LF
              & "           (Frame'First + Stream_Element_Offset"
              & " (GRPC.Framing.Header_Size)" & ASCII.LF
              & "            .. Frame'Last) := Payload (1 .. Cursor.Position);"
              & ASCII.LF
              & "         AWS.Headers.Add (H, ""te"", ""trailers"");"
              & ASCII.LF
              & "         AWS.Headers.Add (H, ""grpc-encoding"", ""identity"");"
              & ASCII.LF
              & "         R := AWS.Client.Post" & ASCII.LF
              & "           (URL          => URL," & ASCII.LF
              & "            Data         => Frame," & ASCII.LF
              & "            Content_Type => ""application/grpc+proto"","
              & ASCII.LF
              & "            Headers      => H," & ASCII.LF
              & "            HTTP_Version => AWS.HTTPv2);" & ASCII.LF
              & "         declare" & ASCII.LF
              & "            Body_Bytes : constant Stream_Element_Array :="
              & ASCII.LF
              & "              AWS.Response.Message_Body (R);" & ASCII.LF
              & "            RC     : Protobuf.IO.Read_Cursor;" & ASCII.LF
              & "            Length : Interfaces.Unsigned_32;" & ASCII.LF
              & "            Flag   : GRPC.Framing.Compression_Flag;"
              & ASCII.LF
              & "         begin" & ASCII.LF
              & "            if Body_Bytes'Length < GRPC.Framing.Header_Size then"
              & ASCII.LF
              & "               raise Program_Error with"
              & " ""response too short for gRPC frame"";" & ASCII.LF
              & "            end if;" & ASCII.LF
              & "            GRPC.Framing.Decode_Header" & ASCII.LF
              & "              (Buffer => Body_Bytes," & ASCII.LF
              & "               Cursor => RC," & ASCII.LF
              & "               Length => Length," & ASCII.LF
              & "               Flag   => Flag);" & ASCII.LF
              & "            " & Out_Pkg & ".Decode" & ASCII.LF
              & "              (Body_Bytes" & ASCII.LF
              & "                 (Body_Bytes'First + RC.Position" & ASCII.LF
              & "                  .. Body_Bytes'First + RC.Position" & ASCII.LF
              & "                     + Stream_Element_Offset (Length) - 1),"
              & ASCII.LF
              & "               Response);" & ASCII.LF
              & "         end;" & ASCII.LF
              & "      end;" & ASCII.LF
              & "   end " & Method_Ident & ";" & ASCII.LF
              & ASCII.LF);
         end;
      end loop;

      Append (Body_Text, "end " & Cli_Pkg & ";" & ASCII.LF);

      declare
         Body_Entry : Plugin.Generated_File;
      begin
         Body_Entry.File_Name := To_Unbounded_String (Stem & ".adb");
         Body_Entry.Content   := Body_Text;
         Files.Append (Body_Entry);
      end;
   end Emit_Client;

   ----------
   -- Emit --
   ----------

   procedure Emit
     (S          : Service_Descriptor;
      Pkg_Prefix : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Svc_Ident : constant String :=
        Codegen.Naming.To_Ada_Identifier (To_String (S.Service_Name));
      Pkg_Name  : constant String := Pkg_Prefix & "." & Svc_Ident;
   begin
      Emit_Base_Spec (S, Pkg_Name, Proto_Pkg, Files);
      Emit_Dispatch  (S, Pkg_Name, Files);
      Emit_Client    (S, Pkg_Name, Files);
   end Emit;

end Codegen.Emit_Service;
