with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;   use Protobuf.Descriptor;

package body Codegen.Emit_Service is

   --  ".helloworld.HelloRequest" → "Helloworld.Hello_Request"
   --  Drops the leading dot, splits on '.', converts each part.
   function Type_Ref_To_Ada (Proto_Type : String) return String;

   function Type_Ref_To_Ada (Proto_Type : String) return String is
      Result : Unbounded_String;
      Buf    : Unbounded_String;
      Start  : Natural := Proto_Type'First;
   begin
      if Start <= Proto_Type'Last and then Proto_Type (Start) = '.' then
         Start := Start + 1;
      end if;
      for I in Start .. Proto_Type'Last loop
         if Proto_Type (I) = '.' then
            Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
            Append (Result, '.');
            Buf := Null_Unbounded_String;
         else
            Append (Buf, Proto_Type (I));
         end if;
      end loop;
      Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
      return To_String (Result) & ".T";
   end Type_Ref_To_Ada;

   ----------
   -- Emit --

   procedure Emit
     (S          : Protobuf.Descriptor.Service_Descriptor;
      Pkg_Prefix : String;
      Proto_Pkg  : String;
      Files      : in out Plugin.Generated_File_Vectors.Vector)
   is
      Svc_Ident  : constant String :=
        Codegen.Naming.To_Ada_Identifier (To_String (S.Service_Name));
      Pkg_Name   : constant String := Pkg_Prefix & "." & Svc_Ident;
      Stem       : constant String := Codegen.Naming.To_File_Stem (Pkg_Name);
      Spec       : Unbounded_String;
      File_Entry : Plugin.Generated_File;

      --  Set of distinct type references we need to `with`.
      Withs      : Unbounded_String;

      procedure Add_With (Pkg : String) is
         Tag : constant String := "with " & Pkg & ";" & ASCII.LF;
      begin
         if Index (Withs, Tag) = 0 then
            Append (Withs, Tag);
         end if;
      end Add_With;

      function Pkg_Of_Ref (Ref : String) return String is
         --  "Helloworld.Hello_Request.T" → "Helloworld.Hello_Request"
         Last_Dot : Natural := 0;
      begin
         for I in reverse Ref'Range loop
            if Ref (I) = '.' then
               Last_Dot := I;
               exit;
            end if;
         end loop;
         if Last_Dot = 0 then
            return Ref;
         end if;
         return Ref (Ref'First .. Last_Dot - 1);
      end Pkg_Of_Ref;
   begin
      --  Walk methods first to collect needed `with` clauses.
      for M of S.Methods loop
         declare
            In_Ref  : constant String := Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Ref : constant String := Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            Add_With (Pkg_Of_Ref (In_Ref));
            Add_With (Pkg_Of_Ref (Out_Ref));
         end;
      end loop;

      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, Withs);
      Append (Spec, ASCII.LF);
      Append (Spec, "package " & Pkg_Name & " is" & ASCII.LF);
      Append (Spec, ASCII.LF);
      Append (Spec, "   --  Fully-qualified path used in the HTTP/2 "
                  & ":path header." & ASCII.LF);
      for M of S.Methods loop
         declare
            Method_Const : constant String :=
              "Path_" & Codegen.Naming.To_Ada_Identifier
                          (To_String (M.Method_Name));
         begin
            Append (Spec,
              "   " & Method_Const & " : constant String := """
              & "/" & Proto_Pkg & "." & To_String (S.Service_Name) & "/"
              & To_String (M.Method_Name) & """;" & ASCII.LF);
         end;
      end loop;

      Append (Spec, ASCII.LF);
      Append (Spec, "   type Service is abstract tagged limited null record;"
                  & ASCII.LF);
      Append (Spec, ASCII.LF);
      for M of S.Methods loop
         declare
            Method_Ident : constant String :=
              Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name));
            In_Ref       : constant String :=
              Type_Ref_To_Ada (To_String (M.Input_Type));
            Out_Ref      : constant String :=
              Type_Ref_To_Ada (To_String (M.Output_Type));
         begin
            Append (Spec,
              "   procedure " & Method_Ident & ASCII.LF
              & "     (Self     : in out Service;" & ASCII.LF
              & "      Request  : " & In_Ref & ";" & ASCII.LF
              & "      Response : out " & Out_Ref & ") is abstract;"
              & ASCII.LF & ASCII.LF);
         end;
      end loop;

      Append (Spec, "end " & Pkg_Name & ";" & ASCII.LF);

      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);
   end Emit;

end Codegen.Emit_Service;
