with Ada.Containers.Vectors;
with Ada.Streams;            use Ada.Streams;
with Ada.Streams.Stream_IO;  use Ada.Streams.Stream_IO;
with Ada.Strings.Unbounded;  use Ada.Strings.Unbounded;
with Ada.Text_IO;
with Codegen.Emit_Enum;
with Codegen.Emit_Message;
with Codegen.Emit_Service;
with Codegen.Naming;
with Codegen.Plugin;
with Protobuf.Descriptor;
with Protobuf.IO;

package body Codegen.Driver is

   package Octet_Vectors is
     new Ada.Containers.Vectors (Positive, Stream_Element);

   --  Stdin/stdout helpers --

   function Read_Stdin return Stream_Element_Array is
      F     : File_Type;
      Chunk : Stream_Element_Array (1 .. 65_536);
      Last  : Stream_Element_Offset;
      V     : Octet_Vectors.Vector;
   begin
      Open (F, In_File, "/dev/stdin");
      loop
         Read (F, Chunk, Last);
         exit when Last < Chunk'First;
         for I in Chunk'First .. Last loop
            V.Append (Chunk (I));
         end loop;
      end loop;
      Close (F);

      declare
         Result : Stream_Element_Array (1 .. Stream_Element_Offset (V.Length));
         Idx    : Stream_Element_Offset := Result'First;
      begin
         for E of V loop
            Result (Idx) := E;
            Idx := Idx + 1;
         end loop;
         return Result;
      end;
   end Read_Stdin;

   procedure Write_Stdout (Bytes : Stream_Element_Array) is
      F : File_Type;
   begin
      Open (F, Out_File, "/dev/stdout");
      Write (F, Bytes);
      Close (F);
   end Write_Stdout;

   --  Match a generation target against the descriptors received --

   function Find_File
     (Files     : Protobuf.Descriptor.File_Vectors.Vector;
      File_Name : Unbounded_String) return Protobuf.Descriptor.File_Descriptor
   is
   begin
      for F of Files loop
         if F.File_Name = File_Name then
            return F;
         end if;
      end loop;
      raise Program_Error with "descriptor not found for " & To_String (File_Name);
   end Find_File;

   --  Emit the empty parent package corresponding to a proto package.
   procedure Emit_Parent_Package
     (Proto_Pkg : Unbounded_String;
      Files     : in out Plugin.Generated_File_Vectors.Vector)
   is
      Ada_Pkg : constant Unbounded_String :=
        Codegen.Naming.Package_To_Ada (To_String (Proto_Pkg));
      Stem    : constant String :=
        Codegen.Naming.To_File_Stem (To_String (Ada_Pkg));
      Spec    : Unbounded_String;
      File_Entry  : Plugin.Generated_File;
   begin
      Append (Spec, "--  Generated by protoc-gen-grpc-ada. Do not edit." & ASCII.LF);
      Append (Spec, "package " & To_String (Ada_Pkg) & " is" & ASCII.LF);
      Append (Spec, "   pragma Pure;" & ASCII.LF);
      Append (Spec, "end " & To_String (Ada_Pkg) & ";" & ASCII.LF);
      File_Entry.File_Name := To_Unbounded_String (Stem & ".ads");
      File_Entry.Content   := Spec;
      Files.Append (File_Entry);
   end Emit_Parent_Package;

   ---------
   -- Run --

   procedure Run is
      Input : constant Protobuf.IO.Octet_Array := Read_Stdin;
      Req   : Codegen.Plugin.Code_Generator_Request;
      Resp  : Codegen.Plugin.Code_Generator_Response;
   begin
      Codegen.Plugin.Decode_Request (Input, Req);

      Ada.Text_IO.Put_Line
        (Ada.Text_IO.Standard_Error,
         "protoc-gen-grpc-ada:"
         & Req.Files_To_Generate.Length'Image
         & " files to generate,"
         & Req.Proto_Files.Length'Image
         & " descriptors received");

      for Target of Req.Files_To_Generate loop
         declare
            File : constant Protobuf.Descriptor.File_Descriptor :=
              Find_File (Req.Proto_Files, Target);
            Pkg  : constant String :=
              To_String (Codegen.Naming.Package_To_Ada
                           (To_String (File.Package_Name)));
         begin
            Emit_Parent_Package (File.Package_Name, Resp.Files);
            for M of File.Messages loop
               Codegen.Emit_Message.Emit (M.all, Pkg, Resp.Files);
            end loop;
            for E of File.Enums loop
               Codegen.Emit_Enum.Emit (E, Pkg, Resp.Files);
            end loop;
            for Svc of File.Services loop
               Codegen.Emit_Service.Emit
                 (Svc, Pkg, To_String (File.Package_Name), Resp.Files);
            end loop;
         end;
      end loop;

      Write_Stdout (Codegen.Plugin.Encode_Response (Resp));
   end Run;

end Codegen.Driver;
