with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Codegen.Naming;
with Protobuf.Descriptor;   use Protobuf.Descriptor;

package body Codegen.Emit_Server_V2 is

   function Type_Ref_To_Ada (Proto_Type : String) return String;
   function Type_Ref_To_Ada (Proto_Type : String) return String is
      Result : Unbounded_String;
      Buf    : Unbounded_String;
      Start  : Natural := Proto_Type'First;
   begin
      if Start <= Proto_Type'Last and then Proto_Type (Start) = '.' then
         Start := Start + 1;
      end if;
      for I in Start .. Proto_Type'Last loop
         if Proto_Type (I) = '.' then
            Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
            Append (Result, '.');
            Buf := Null_Unbounded_String;
         else
            Append (Buf, Proto_Type (I));
         end if;
      end loop;
      Append (Result, Codegen.Naming.To_Ada_Identifier (To_String (Buf)));
      return To_String (Result);
   end Type_Ref_To_Ada;

   procedure Add_With (W : in out Unbounded_String; Pkg : String) is
      Tag : constant String := "with " & Pkg & ";" & ASCII.LF;
   begin
      if Index (W, Tag) = 0 then Append (W, Tag); end if;
   end Add_With;

   function MA (M : Method_Descriptor) return String is
     (Codegen.Naming.To_Ada_Identifier (To_String (M.Method_Name)));

   function Is_Unary (M : Method_Descriptor) return Boolean is
     (not M.Server_Streaming and then not M.Client_Streaming);

   ----------
   -- Emit --
   ----------

   procedure Emit
     (S        : Protobuf.Descriptor.Service_Descriptor;
      Pkg_Name : String;
      Files    : in out Plugin.Generated_File_Vectors.Vector)
   is
      Srv_Pkg : constant String := Pkg_Name & ".Server";
      Stem    : constant String := Codegen.Naming.To_File_Stem (Srv_Pkg);
      Spec    : Unbounded_String;
      Bod     : Unbounded_String;
      S_W     : Unbounded_String;
      B_W     : Unbounded_String;
   begin
      Add_With (S_W, "RFLX.RFLX_Types");
      for M of S.Methods loop
         if Is_Unary (M) then
            Add_With (S_W, Type_Ref_To_Ada (To_String (M.Input_Type)));
            Add_With (S_W, Type_Ref_To_Ada (To_String (M.Output_Type)));
         end if;
      end loop;

      Add_With (B_W, "Ada.Streams");
      Add_With (B_W, "Ada.Text_IO");
      Add_With (B_W, "Ada.Unchecked_Deallocation");
      Add_With (B_W, "Grpc_Core.Framing");
      Add_With (B_W, "Http2_Core.Hpack");
      Add_With (B_W, "Http2_Core.Server");
      Add_With (B_W, "Protobuf.IO");
      Add_With (B_W, Pkg_Name);
      for M of S.Methods loop
         if Is_Unary (M) then
            Add_With (B_W, Type_Ref_To_Ada (To_String (M.Input_Type)));
            Add_With (B_W, Type_Ref_To_Ada (To_String (M.Output_Type)));
         end if;
      end loop;

      --  Spec ---------------------------------------------------
      Append (Spec, "--  Generated by protoc-gen-grpc-ada"
                    & " (v2 server). Do not edit." & ASCII.LF);
      Append (Spec, S_W & ASCII.LF);
      Append (Spec, "package " & Srv_Pkg & " is" & ASCII.LF & ASCII.LF);

      --  Build the formal-parameter list for a generic Run procedure.
      Append (Spec, "   generic" & ASCII.LF);
      for M of S.Methods loop
         if Is_Unary (M) then
            declare
               In_T  : constant String :=
                 Type_Ref_To_Ada (To_String (M.Input_Type)) & ".T";
               Out_T : constant String :=
                 Type_Ref_To_Ada (To_String (M.Output_Type)) & ".T";
            begin
               Append (Spec,
                 "      with procedure " & MA (M) & ASCII.LF
                 & "        (Request  : " & In_T & ";" & ASCII.LF
                 & "         Response : out " & Out_T & ");" & ASCII.LF);
            end;
         end if;
      end loop;
      Append (Spec, "   procedure Run" & ASCII.LF
                    & "     (Host : String := ""0.0.0.0"";" & ASCII.LF
                    & "      Port : Natural := 50051);" & ASCII.LF
                    & ASCII.LF);

      Append (Spec, "end " & Srv_Pkg & ";" & ASCII.LF);

      --  Body ---------------------------------------------------
      Append (Bod, "--  Generated by protoc-gen-grpc-ada"
                   & " (v2 server). Do not edit." & ASCII.LF);
      Append (Bod, B_W & ASCII.LF);
      Append (Bod, "package body " & Srv_Pkg & " is" & ASCII.LF & ASCII.LF);
      Append (Bod, "   use type RFLX.RFLX_Types.Index;" & ASCII.LF);
      Append (Bod, "   use type Ada.Streams.Stream_Element_Offset;"
                   & ASCII.LF);
      Append (Bod, "   Buf_Size : constant := 4 * 1024 * 1024 + 64;"
                   & ASCII.LF);
      Append (Bod, "   Max_Msg  : constant := 4 * 1024 * 1024;"
                   & ASCII.LF & ASCII.LF);

      --  RFLX → Octet_Array (Stream_Element_Array) helper.
      Append (Bod,
        "   function To_Pb" & ASCII.LF
        & "     (R : RFLX.RFLX_Types.Bytes)" & ASCII.LF
        & "      return Protobuf.IO.Octet_Array" & ASCII.LF
        & "   is" & ASCII.LF
        & "      S : Protobuf.IO.Octet_Array" & ASCII.LF
        & "        (1 .. Ada.Streams.Stream_Element_Offset (R'Length));"
        & ASCII.LF
        & "   begin" & ASCII.LF
        & "      for K in 0 .. Natural (R'Length) - 1 loop" & ASCII.LF
        & "         S (S'First + Ada.Streams.Stream_Element_Offset (K))"
        & " :=" & ASCII.LF
        & "           Protobuf.IO.Octet" & ASCII.LF
        & "             (R (R'First +"
        & " RFLX.RFLX_Types.Index'Base (K)));" & ASCII.LF
        & "      end loop;" & ASCII.LF
        & "      return S;" & ASCII.LF
        & "   end To_Pb;" & ASCII.LF & ASCII.LF);

      Append (Bod,
        "   procedure Run" & ASCII.LF
        & "     (Host : String := ""0.0.0.0"";" & ASCII.LF
        & "      Port : Natural := 50051)" & ASCII.LF
        & "   is" & ASCII.LF
        & "      L : Http2_Core.Server.Listener;" & ASCII.LF
        & "      Buf : RFLX.RFLX_Types.Bytes_Ptr :=" & ASCII.LF
        & "        new RFLX.RFLX_Types.Bytes'(1 .. Buf_Size => 0);"
        & ASCII.LF
        & "      In_Buf : RFLX.RFLX_Types.Bytes_Ptr :=" & ASCII.LF
        & "        new RFLX.RFLX_Types.Bytes'(1 .. Buf_Size => 0);"
        & ASCII.LF
        & "      Out_Buf : RFLX.RFLX_Types.Bytes_Ptr :=" & ASCII.LF
        & "        new RFLX.RFLX_Types.Bytes'(1 .. Buf_Size => 0);"
        & ASCII.LF & ASCII.LF
        & "      procedure Handle" & ASCII.LF
        & "        (Request_Headers       :"
        & " Http2_Core.Hpack.Header_Block;" & ASCII.LF
        & "         Request_Headers_Last  : Natural;" & ASCII.LF
        & "         Request_Body          : RFLX.RFLX_Types.Bytes;"
        & ASCII.LF
        & "         Request_Body_Last     : Natural;" & ASCII.LF
        & "         Response_Headers      :"
        & " in out Http2_Core.Hpack.Header_Block;" & ASCII.LF
        & "         Response_Headers_Last : out Natural;" & ASCII.LF
        & "         Response_Body         :"
        & " in out RFLX.RFLX_Types.Bytes;" & ASCII.LF
        & "         Response_Body_Last    : out Natural;" & ASCII.LF
        & "         Trailers              :"
        & " in out Http2_Core.Hpack.Header_Block;" & ASCII.LF
        & "         Trailers_Last         : out Natural)" & ASCII.LF
        & "      is" & ASCII.LF
        & "         Path : String (1 .. 256) := (others => ' ');"
        & ASCII.LF
        & "         Path_Len : Natural := 0;" & ASCII.LF
        & "      begin" & ASCII.LF
        & "         for I in Request_Headers'First"
        & " .. Request_Headers_Last loop" & ASCII.LF
        & "            declare" & ASCII.LF
        & "               H : Http2_Core.Hpack.Header_Field renames"
        & ASCII.LF
        & "                 Request_Headers (I);" & ASCII.LF
        & "            begin" & ASCII.LF
        & "               if H.Name (1 .. H.Name_Last) = "":path"" then"
        & ASCII.LF
        & "                  Path (1 .. H.Value_Last) :=" & ASCII.LF
        & "                    H.Value (1 .. H.Value_Last);" & ASCII.LF
        & "                  Path_Len := H.Value_Last;" & ASCII.LF
        & "               end if;" & ASCII.LF
        & "            end;" & ASCII.LF
        & "         end loop;" & ASCII.LF & ASCII.LF
        & "         Response_Headers (Response_Headers'First) :=" & ASCII.LF
        & "           Http2_Core.Hpack.Make_Header"
        & " ("":status"", ""200"");" & ASCII.LF
        & "         Response_Headers (Response_Headers'First + 1) :="
        & ASCII.LF
        & "           Http2_Core.Hpack.Make_Header" & ASCII.LF
        & "             (""content-type"", ""application/grpc"");" & ASCII.LF
        & "         Response_Headers_Last :="
        & " Response_Headers'First + 1;" & ASCII.LF
        & "         Trailers (Trailers'First) :=" & ASCII.LF
        & "           Http2_Core.Hpack.Make_Header"
        & " (""grpc-status"", ""0"");" & ASCII.LF
        & "         Trailers_Last := Trailers'First;" & ASCII.LF
        & "         Response_Body_Last :="
        & " Natural (Response_Body'First) - 1;" & ASCII.LF & ASCII.LF);

      --  Per-method dispatch
      for M of S.Methods loop
         if Is_Unary (M) then
            declare
               In_Pkg  : constant String :=
                 Type_Ref_To_Ada (To_String (M.Input_Type));
               Out_Pkg : constant String :=
                 Type_Ref_To_Ada (To_String (M.Output_Type));
               Path    : constant String :=
                 Pkg_Name & ".Path_" & MA (M);
            begin
               Append (Bod,
                 "         if Path (1 .. Path_Len) = "
                 & Path & " then" & ASCII.LF
                 & "            declare" & ASCII.LF
                 & "               Req : " & In_Pkg & ".T;" & ASCII.LF
                 & "               Rep : " & Out_Pkg & ".T;" & ASCII.LF
                 & "               PB_In : constant Protobuf.IO.Octet_Array"
                 & ASCII.LF
                 & "                 := To_Pb (Request_Body"
                 & " (Request_Body'First + 5 .." & ASCII.LF
                 & "                          RFLX.RFLX_Types.Index"
                 & " (Request_Body_Last)));"
                 & ASCII.LF
                 & "               type PB_Out_Ptr is access"
                 & " Protobuf.IO.Octet_Array;" & ASCII.LF
                 & "               procedure Free is new"
                 & " Ada.Unchecked_Deallocation" & ASCII.LF
                 & "                 (Protobuf.IO.Octet_Array,"
                 & " PB_Out_Ptr);" & ASCII.LF
                 & "               PB_Out : PB_Out_Ptr := new"
                 & ASCII.LF
                 & "                 Protobuf.IO.Octet_Array"
                 & " (1 .. Max_Msg);" & ASCII.LF
                 & "               Cur : Protobuf.IO.Write_Cursor;" & ASCII.LF
                 & "            begin" & ASCII.LF
                 & "               " & In_Pkg & ".Decode (PB_In, Req);"
                 & ASCII.LF
                 & "               " & MA (M) & " (Req, Rep);" & ASCII.LF
                 & "               " & Out_Pkg
                 & ".Encode (Rep, PB_Out.all, Cur);" & ASCII.LF
                 & "               --  gRPC frame: 1B flag + 4B BE length."
                 & ASCII.LF
                 & "               Response_Body (Response_Body'First) := 0;"
                 & ASCII.LF
                 & "               declare" & ASCII.LF
                 & "                  L : constant Natural :="
                 & " Natural (Cur.Position);" & ASCII.LF
                 & "               begin" & ASCII.LF
                 & "                  Response_Body"
                 & " (Response_Body'First + 1) :=" & ASCII.LF
                 & "                    RFLX.RFLX_Types.Byte"
                 & " (L / (2**24));" & ASCII.LF
                 & "                  Response_Body"
                 & " (Response_Body'First + 2) :=" & ASCII.LF
                 & "                    RFLX.RFLX_Types.Byte"
                 & " ((L / (2**16)) mod 256);" & ASCII.LF
                 & "                  Response_Body"
                 & " (Response_Body'First + 3) :=" & ASCII.LF
                 & "                    RFLX.RFLX_Types.Byte"
                 & " ((L / (2**8)) mod 256);" & ASCII.LF
                 & "                  Response_Body"
                 & " (Response_Body'First + 4) :=" & ASCII.LF
                 & "                    RFLX.RFLX_Types.Byte (L mod 256);"
                 & ASCII.LF
                 & "                  for I in 1 .. L loop" & ASCII.LF
                 & "                     Response_Body" & ASCII.LF
                 & "                       (Response_Body'First + 4"
                 & " + RFLX.RFLX_Types.Index (I)) :=" & ASCII.LF
                 & "                         RFLX.RFLX_Types.Byte"
                 & " (PB_Out (Ada.Streams." & ASCII.LF
                 & "                           Stream_Element_Offset"
                 & " (I)));" & ASCII.LF
                 & "                  end loop;" & ASCII.LF
                 & "                  Response_Body_Last :=" & ASCII.LF
                 & "                    Natural (Response_Body'First)"
                 & " + 4 + L;" & ASCII.LF
                 & "               end;" & ASCII.LF
                 & "               Free (PB_Out);" & ASCII.LF
                 & "            end;" & ASCII.LF
                 & "         end if;" & ASCII.LF & ASCII.LF);
            end;
         end if;
      end loop;

      Append (Bod, "      end Handle;" & ASCII.LF & ASCII.LF);

      Append (Bod,
        "      procedure Serve_One is new" & ASCII.LF
        & "        Http2_Core.Server.Accept_And_Serve"
        & " (Handle_Request => Handle);" & ASCII.LF & ASCII.LF
        & "   begin" & ASCII.LF
        & "      Http2_Core.Server.Attach_Buffers" & ASCII.LF
        & "        (L, Buf, In_Buf, Out_Buf);" & ASCII.LF
        & "      Http2_Core.Server.Listen (L, Host, Port);" & ASCII.LF
        & "      Ada.Text_IO.Put_Line" & ASCII.LF
        & "        (""" & Srv_Pkg & " listening on"
        & " "" & Host & "":"" & Port'Image);" & ASCII.LF
        & "      loop" & ASCII.LF
        & "         Serve_One (L);" & ASCII.LF
        & "      end loop;" & ASCII.LF
        & "   end Run;" & ASCII.LF & ASCII.LF);

      Append (Bod, "end " & Srv_Pkg & ";" & ASCII.LF);

      declare
         SF : Plugin.Generated_File;
         BF : Plugin.Generated_File;
      begin
         SF.File_Name := To_Unbounded_String (Stem & ".ads");
         SF.Content   := Spec;
         BF.File_Name := To_Unbounded_String (Stem & ".adb");
         BF.Content   := Bod;
         Files.Append (SF);
         Files.Append (BF);
      end;
   end Emit;

end Codegen.Emit_Server_V2;
