--  http2_core_fuzz — random-bytes-in fuzzer for the hand-written
--  HPACK / Huffman / Int_Codec codecs.
--
--  Goal: validate the SPARK proof's claim that these decoders
--  cannot crash on malformed input. Every input is a randomly-
--  generated byte sequence; every decode call must terminate
--  with either Output_OK = True (somehow valid) or
--  Output_OK = False, but NEVER raise an unhandled exception.
--
--  We catch CONSTRAINT_ERROR, STORAGE_ERROR, PROGRAM_ERROR
--  explicitly and log the input on hit. A clean SPARK proof
--  predicts zero hits.
--
--  Each iteration:
--    1. Generate a random byte sequence of random length 1..256.
--    2. Run it through Hpack.Decode, Huffman.Decode,
--       Int_Codec.Decode (each prefix N=4..7), and
--       Grpc_Core-style framing decode would go through grpc_core_tests.
--    3. Increment counters by outcome.
--
--  Reads target iteration count from argv[1] (default 1_000_000).
--  Writes a summary line on each progress milestone.

with Ada.Text_IO;
with Ada.Command_Line;
with Ada.Numerics.Discrete_Random;
with Ada.Calendar;
with Ada.Exceptions;
with Interfaces;

with RFLX.RFLX_Types;

with Http2_Core.Hpack;
with Http2_Core.Hpack.Huffman;
with Http2_Core.Hpack.Int_Codec;

procedure Http2_Core_Fuzz is
   use Ada.Text_IO;
   use Ada.Calendar;

   package Byte_Random is new
     Ada.Numerics.Discrete_Random (Interfaces.Unsigned_8);
   package Length_Random is new
     Ada.Numerics.Discrete_Random (Positive);

   Byte_Gen : Byte_Random.Generator;
   Len_Gen  : Length_Random.Generator;

   --  Aggregate counters per decoder.
   type Outcome_Count is record
      Total       : Natural := 0;
      OK_True     : Natural := 0;  --  decoded as valid
      OK_False    : Natural := 0;  --  rejected cleanly
      Constraint  : Natural := 0;  --  CONSTRAINT_ERROR raised
      Storage     : Natural := 0;  --  STORAGE_ERROR raised
      Program     : Natural := 0;  --  PROGRAM_ERROR raised
      Other       : Natural := 0;  --  any other exception
   end record;

   Hpack_R    : Outcome_Count;
   Huffman_R  : Outcome_Count;
   Int_R      : array (4 .. 7) of Outcome_Count;

   --  Sample up to N (default 1M) random inputs.
   Iterations : Natural := 1_000_000;

   ----------------------------------------------------------------
   --  Logging — append-only file so we can tail it during the run.
   ----------------------------------------------------------------

   Crash_Log : File_Type;

   procedure Log_Crash
     (Decoder : String;
      Bytes   : RFLX.RFLX_Types.Bytes;
      Why     : String);

   procedure Log_Crash
     (Decoder : String;
      Bytes   : RFLX.RFLX_Types.Bytes;
      Why     : String)
   is
   begin
      Put (Crash_Log,
           "CRASH " & Decoder & " " & Why & " bytes=");
      for B of Bytes loop
         declare
            Hex : constant String := "0123456789abcdef";
            N   : constant Natural := Natural (B);
         begin
            Put (Crash_Log, Hex (Hex'First + N / 16));
            Put (Crash_Log, Hex (Hex'First + N mod 16));
         end;
      end loop;
      New_Line (Crash_Log);
      Flush (Crash_Log);
   end Log_Crash;

   ----------------------------------------------------------------
   --  Per-iteration body. Generates one input, runs every decoder.
   ----------------------------------------------------------------

   procedure One_Iteration;

   procedure One_Iteration is
      Len : constant Positive :=
        (Length_Random.Random (Len_Gen) mod 256) + 1;
      Buf : RFLX.RFLX_Types.Bytes
        (1 .. RFLX.RFLX_Types.Index (Len));
   begin
      for I in Buf'Range loop
         Buf (I) := RFLX.RFLX_Types.Byte
                      (Byte_Random.Random (Byte_Gen));
      end loop;

      --  Hpack.Decode
      Hpack_R.Total := Hpack_R.Total + 1;
      declare
         Hdrs : Http2_Core.Hpack.Header_Block (1 .. 16);
         HL   : Natural;
         OK   : Boolean;
         Hpack_Buf : Http2_Core.Hpack.Octet_Array (1 .. Buf'Length);
      begin
         for I in Hpack_Buf'Range loop
            Hpack_Buf (I) := Http2_Core.Hpack.Octet
                               (Buf (RFLX.RFLX_Types.Index (I)));
         end loop;
         declare
            DT : Http2_Core.Hpack.Dynamic_Table.Table;
         begin
            Http2_Core.Hpack.Decode
              (Input         => Hpack_Buf,
               Headers       => Hdrs,
               Headers_Last  => HL,
               Output_OK     => OK,
               Decoder_State => DT);
         end;
         if OK then
            Hpack_R.OK_True := Hpack_R.OK_True + 1;
         else
            Hpack_R.OK_False := Hpack_R.OK_False + 1;
         end if;
      exception
         when E : Constraint_Error =>
            Hpack_R.Constraint := Hpack_R.Constraint + 1;
            Log_Crash ("Hpack.Decode", Buf,
                       "Constraint_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : Storage_Error =>
            Hpack_R.Storage := Hpack_R.Storage + 1;
            Log_Crash ("Hpack.Decode", Buf,
                       "Storage_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : Program_Error =>
            Hpack_R.Program := Hpack_R.Program + 1;
            Log_Crash ("Hpack.Decode", Buf,
                       "Program_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : others =>
            Hpack_R.Other := Hpack_R.Other + 1;
            Log_Crash ("Hpack.Decode", Buf,
                       Ada.Exceptions.Exception_Name (E)
                       & ": "
                       & Ada.Exceptions.Exception_Message (E));
      end;

      --  Huffman.Decode
      Huffman_R.Total := Huffman_R.Total + 1;
      declare
         Huff_Out : Http2_Core.Hpack.Huffman.Octet_Array
                      (1 .. Buf'Length * 2 + 8);
         Huff_In  : Http2_Core.Hpack.Huffman.Octet_Array
                      (1 .. Buf'Length);
         L        : Natural;
         OK       : Boolean;
      begin
         for I in Huff_In'Range loop
            Huff_In (I) := Http2_Core.Hpack.Huffman.Octet
                             (Buf (RFLX.RFLX_Types.Index (I)));
         end loop;
         Http2_Core.Hpack.Huffman.Decode
           (Input       => Huff_In,
            Output      => Huff_Out,
            Output_Last => L,
            Output_OK   => OK);
         if OK then
            Huffman_R.OK_True := Huffman_R.OK_True + 1;
         else
            Huffman_R.OK_False := Huffman_R.OK_False + 1;
         end if;
      exception
         when E : Constraint_Error =>
            Huffman_R.Constraint := Huffman_R.Constraint + 1;
            Log_Crash ("Huffman.Decode", Buf,
                       "Constraint_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : Storage_Error =>
            Huffman_R.Storage := Huffman_R.Storage + 1;
            Log_Crash ("Huffman.Decode", Buf,
                       "Storage_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : Program_Error =>
            Huffman_R.Program := Huffman_R.Program + 1;
            Log_Crash ("Huffman.Decode", Buf,
                       "Program_Error: " &
                       Ada.Exceptions.Exception_Message (E));
         when E : others =>
            Huffman_R.Other := Huffman_R.Other + 1;
            Log_Crash ("Huffman.Decode", Buf,
                       Ada.Exceptions.Exception_Name (E)
                       & ": "
                       & Ada.Exceptions.Exception_Message (E));
      end;

      --  Int_Codec.Decode for every prefix width.
      for N in 4 .. 7 loop
         Int_R (N).Total := Int_R (N).Total + 1;
         declare
            IC_Buf : Http2_Core.Hpack.Int_Codec.Octet_Array
                       (1 .. Buf'Length);
            V      : Natural;
            L      : Natural;
            OK     : Boolean;
         begin
            for I in IC_Buf'Range loop
               IC_Buf (I) := Http2_Core.Hpack.Int_Codec.Octet
                               (Buf (RFLX.RFLX_Types.Index (I)));
            end loop;
            Http2_Core.Hpack.Int_Codec.Decode
              (Input     => IC_Buf,
               First     => 1,
               N         => N,
               Value     => V,
               Last      => L,
               Output_OK => OK);
            if OK then
               Int_R (N).OK_True := Int_R (N).OK_True + 1;
            else
               Int_R (N).OK_False := Int_R (N).OK_False + 1;
            end if;
         exception
            when E : Constraint_Error =>
               Int_R (N).Constraint := Int_R (N).Constraint + 1;
               Log_Crash ("Int_Codec.Decode N=" & N'Image, Buf,
                          "Constraint_Error: " &
                          Ada.Exceptions.Exception_Message (E));
            when E : Storage_Error =>
               Int_R (N).Storage := Int_R (N).Storage + 1;
               Log_Crash ("Int_Codec.Decode N=" & N'Image, Buf,
                          "Storage_Error: " &
                          Ada.Exceptions.Exception_Message (E));
            when E : Program_Error =>
               Int_R (N).Program := Int_R (N).Program + 1;
               Log_Crash ("Int_Codec.Decode N=" & N'Image, Buf,
                          "Program_Error: " &
                          Ada.Exceptions.Exception_Message (E));
            when E : others =>
               Int_R (N).Other := Int_R (N).Other + 1;
               Log_Crash ("Int_Codec.Decode N=" & N'Image, Buf,
                          Ada.Exceptions.Exception_Name (E)
                          & ": "
                          & Ada.Exceptions.Exception_Message (E));
         end;
      end loop;
   end One_Iteration;

   ----------------------------------------------------------------
   --  Pretty-print per-decoder results.
   ----------------------------------------------------------------

   procedure Report (Label : String; R : Outcome_Count);
   procedure Report (Label : String; R : Outcome_Count) is
   begin
      Put_Line (Label
                & ": total=" & R.Total'Image
                & " OK_True=" & R.OK_True'Image
                & " OK_False=" & R.OK_False'Image
                & " Constraint=" & R.Constraint'Image
                & " Storage=" & R.Storage'Image
                & " Program=" & R.Program'Image
                & " Other=" & R.Other'Image);
   end Report;

   Start_Time : Time;

begin
   if Ada.Command_Line.Argument_Count >= 1 then
      Iterations := Natural'Value (Ada.Command_Line.Argument (1));
   end if;

   Byte_Random.Reset (Byte_Gen, 17);
   Length_Random.Reset (Len_Gen, 42);
   Create (Crash_Log, Out_File, "fuzz_crashes.log");
   Put_Line (Crash_Log, "# http2_core_fuzz crash log");
   Flush (Crash_Log);

   Put_Line ("http2_core_fuzz: " & Iterations'Image & " iterations");
   Start_Time := Clock;

   for I in 1 .. Iterations loop
      One_Iteration;
      if I mod 10_000 = 0 then
         Put_Line
           ("[" & I'Image & "]"
            & " elapsed=" & Duration'Image (Clock - Start_Time) & "s");
      end if;
   end loop;

   Put_Line ("=== final ===");
   Report ("Hpack.Decode  ", Hpack_R);
   Report ("Huffman.Decode", Huffman_R);
   Report ("Int_Codec N=4 ", Int_R (4));
   Report ("Int_Codec N=5 ", Int_R (5));
   Report ("Int_Codec N=6 ", Int_R (6));
   Report ("Int_Codec N=7 ", Int_R (7));

   Close (Crash_Log);
end Http2_Core_Fuzz;
