name = "grpc_core_tests"
description = "Tests for grpc_core"
version = "0.0.1"

authors = ["Mathis Sperlich"]
maintainers = ["Mathis Sperlich <sperlich.mathis@gmail.com>"]
maintainers-logins = ["mathis"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"

executables = ["grpc_core_tests", "grpc_core_fuzz"]
project-files = ["grpc_core_tests.gpr"]

[[depends-on]]
grpc_core = "*"

[[pins]]
grpc_core = { path = "../grpc_core" }
