------------------------------------------------------------------------------
--                                                                          --
--               Generated by RecordFlux 0.26.0 on 2026-05-02               --
--                                                                          --
--                     Copyright (C) 2018-2026 AdaCore                      --
--                                                                          --
--         SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception          --
--                                                                          --
------------------------------------------------------------------------------

pragma Style_Checks ("N3aAbCdefhiIklnOprStux");
pragma Warnings (Off, """Always_Terminates"" is not a valid aspect identifier");

package RFLX.RFLX_Builtin_Types
with
  SPARK_Mode,
  Always_Terminates
is

   type Length is new Natural;

   type Index is new Length range 1 .. Length'Last;

   type Byte is mod 2**8;

   type Bytes is array (Index range <>) of Byte;

   type Bytes_Ptr is access Bytes;
   --  Original RecordFlux-generated declaration. Pool-specific
   --  access type → heap allocation only. For bare-metal targets
   --  this means any code that takes a Bytes_Ptr parameter
   --  cannot be called with a static buffer. The clean fix is to
   --  refactor the protocol API to take `in out Bytes` slices
   --  instead of `Bytes_Ptr`; tracked as a separate follow-up
   --  on the bare-metal track. An earlier attempt to relax this
   --  to `access all Bytes` plus 'Unchecked_Access / address-cast
   --  failed because Bytes_Ptr designates an UNCONSTRAINED array
   --  type — the bounds (dope vector) live IN the access value
   --  itself, not in the pointee, and bare 'Address conversion
   --  doesn't carry them.

   type Bit_Length is range 0 .. Length'Last * 8;

   type Boolean_Base is mod 2;

end RFLX.RFLX_Builtin_Types;
