name = "examples"
description = "transports-spark example programs"
version = "0.0.1"

authors = ["Mathis Sperlich"]
maintainers = ["Mathis Sperlich <sperlich.mathis@gmail.com>"]
maintainers-logins = ["mathis"]
licenses = "MIT"

executables = ["greeter_server", "greeter_client",
               "greeter_client_v02",
               "greeter_streaming_demo",
               "greeter_bench_client",
               "greeter_server_v02",
               "greeter_streaming_server",
               "greeter_mux_server",
               "http1_demo",
               "mqtt_broker_demo",
               "listfeatures_server", "listfeatures_client",
               "mqtt_demo"]
project-files = ["examples.gpr"]

[[depends-on]]
grpc_ada = "*"

[[depends-on]]
mqtt_core = "*"

[[depends-on]]
http2_core = "*"

[[depends-on]]
http1_core = "*"

[[depends-on]]
grpc_core = "*"

[[pins]]
grpc_ada = { path = "../grpc_ada" }

[pins.mqtt_core]
path = "../mqtt_core"

[pins.http2_core]
path = "../http2_core"

[pins.http1_core]
path = "../http1_core"

[pins.grpc_core]
path = "../grpc_core"
