name = "rflx_runtime"
description = "Shared RecordFlux runtime support files"
version = "0.0.1"

authors = ["Mathis Sperlich"]
maintainers = ["Mathis Sperlich <sperlich.mathis@gmail.com>"]
maintainers-logins = ["mathis"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"

project-files = ["rflx_runtime.gpr"]
